# Pipeline para construir un proyecto Node.js con React en Azure DevOps
trigger:
- master

pool:
  name: Default
  demands: agent.name -equals agente
steps:
- script: echo Hello, world!
  displayName: 'Run on line Script'
