trigger:
- master

pool:
  name: Default
  demands: agent.name -equals agente

stages:
  - stage: Prebuild
    displayName: "Prepare Environment"
    jobs:
      - job: Setup_Node
        displayName: "Setup Node and install dependencies"
        steps:
          - script: node -v
            displayName: "Check Node.js Version"
          
          - script: npm install
            displayName: "Install Dependencies"
          
          - script: npm list next
            displayName: "Check if Next.js is installed"

  - stage: Build
    displayName: "Building the app"
    dependsOn: Prebuild
    jobs:
      - job: Build_Next
        displayName: "Build Next.js App"
        steps:
          - script: npm ci
            displayName: "Ensure Dependencies Installed"

          - script: ls -la
            displayName: "Check Directory Contents"

          - script: npm run build
            displayName: "Run Next.js Build"

          - task: PublishBuildArtifacts@1
            displayName: "Publish Build Artifacts"
            inputs:
              pathtoPublish: ".next"
              artifactName: "flatris-app"
