trigger:
  - main  

pool:
  name: Default
  demands: agent.name -equals agente

stages:
  - stage: Prebuild
    displayName: "Prepare Environment"
    jobs:
      - job: Setup_Node
        displayName: "Setup Node and Install Dependencies"
        steps:
          - script: node -v
            displayName: "Check Node.js Version"

          - script: |
              cd frontend
              npm ci
            displayName: "Install Dependencies in frontend"


  - stage: Build
    displayName: "Building the Angular App"
    dependsOn: Prebuild
    jobs:
      - job: Build_Angular
        displayName: "Build Angular App"
        steps:
          - script: |
              cd frontend
              ls -la
            displayName: "Check Directory Contents"

          - script: |
              cd frontend
              npm run build -- --configuration=production
            displayName: "Run Angular Build"

          - task: PublishBuildArtifacts@1
            displayName: "Publish Build Artifacts"
            inputs:
              pathtoPublish: "frontend/dist"
              artifactName: "angular-app"
